
services:
- type: web
  name: prenatal-whatsapp-bot
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
  healthCheckPath: /health
  autoDeploy: true
  envVars:
  - key: DB_PATH
    value: prenatal.db
